import type { Zona } from '../lib/tipos'

/**
 * Las 104 zonas reales del cuadro de deliverys.
 *
 * Generado desde supabase/migrations/0003_datos_iniciales.sql — si el cuadro
 * cambia allá, hay que regenerar este archivo.
 */
export const ZONAS_DEMO: Zona[] = [
  { id: 'z0', nombre: 'Panteón', tarifa_cliente_usd: 2.00, pago_repartidor_usd: 2.00, orden: 20, activo: true },
  { id: 'z1', nombre: 'Lecuna', tarifa_cliente_usd: 2.00, pago_repartidor_usd: 2.00, orden: 20, activo: true },
  { id: 'z2', nombre: 'Urdaneta', tarifa_cliente_usd: 2.00, pago_repartidor_usd: 2.00, orden: 20, activo: true },
  { id: 'z3', nombre: 'Av. Universidad', tarifa_cliente_usd: 2.00, pago_repartidor_usd: 2.00, orden: 20, activo: true },
  { id: 'z4', nombre: 'Bellas Artes', tarifa_cliente_usd: 2.00, pago_repartidor_usd: 2.00, orden: 20, activo: true },
  { id: 'z5', nombre: 'San Bernardino', tarifa_cliente_usd: 2.00, pago_repartidor_usd: 2.00, orden: 20, activo: true },
  { id: 'z6', nombre: 'Nuevo Circo', tarifa_cliente_usd: 2.00, pago_repartidor_usd: 2.00, orden: 20, activo: true },
  { id: 'z7', nombre: 'San Agustín', tarifa_cliente_usd: 2.00, pago_repartidor_usd: 2.00, orden: 20, activo: true },
  { id: 'z8', nombre: 'La Hoyada', tarifa_cliente_usd: 2.00, pago_repartidor_usd: 2.00, orden: 20, activo: true },
  { id: 'z9', nombre: 'Baralt', tarifa_cliente_usd: 3.00, pago_repartidor_usd: 3.00, orden: 30, activo: true },
  { id: 'z10', nombre: 'Qta. Crespo', tarifa_cliente_usd: 3.00, pago_repartidor_usd: 3.00, orden: 30, activo: true },
  { id: 'z11', nombre: 'La Pastora', tarifa_cliente_usd: 3.00, pago_repartidor_usd: 3.00, orden: 30, activo: true },
  { id: 'z12', nombre: 'Puente Medina', tarifa_cliente_usd: 3.00, pago_repartidor_usd: 3.00, orden: 30, activo: true },
  { id: 'z13', nombre: 'La Charneca', tarifa_cliente_usd: 3.00, pago_repartidor_usd: 3.00, orden: 30, activo: true },
  { id: 'z14', nombre: 'Cotiza', tarifa_cliente_usd: 3.00, pago_repartidor_usd: 3.00, orden: 30, activo: true },
  { id: 'z15', nombre: 'Altagracia', tarifa_cliente_usd: 3.00, pago_repartidor_usd: 3.00, orden: 30, activo: true },
  { id: 'z16', nombre: 'Loblán', tarifa_cliente_usd: 3.00, pago_repartidor_usd: 3.00, orden: 30, activo: true },
  { id: 'z17', nombre: 'Pinto Salinas', tarifa_cliente_usd: 3.00, pago_repartidor_usd: 3.00, orden: 30, activo: true },
  { id: 'z18', nombre: 'Maripérez', tarifa_cliente_usd: 3.00, pago_repartidor_usd: 3.00, orden: 30, activo: true },
  { id: 'z19', nombre: 'La Florida', tarifa_cliente_usd: 3.00, pago_repartidor_usd: 3.00, orden: 30, activo: true },
  { id: 'z20', nombre: 'Libertador', tarifa_cliente_usd: 3.00, pago_repartidor_usd: 3.00, orden: 30, activo: true },
  { id: 'z21', nombre: 'Andrés Bello', tarifa_cliente_usd: 3.00, pago_repartidor_usd: 3.00, orden: 30, activo: true },
  { id: 'z22', nombre: 'Caño Amarillo', tarifa_cliente_usd: 3.00, pago_repartidor_usd: 3.00, orden: 30, activo: true },
  { id: 'z23', nombre: 'Av. Sucre', tarifa_cliente_usd: 3.00, pago_repartidor_usd: 3.00, orden: 30, activo: true },
  { id: 'z24', nombre: 'Av. San Martín', tarifa_cliente_usd: 3.00, pago_repartidor_usd: 3.00, orden: 30, activo: true },
  { id: 'z25', nombre: 'Boyacá', tarifa_cliente_usd: 3.00, pago_repartidor_usd: 3.00, orden: 30, activo: true },
  { id: 'z26', nombre: 'El Paraíso', tarifa_cliente_usd: 3.00, pago_repartidor_usd: 3.00, orden: 30, activo: true },
  { id: 'z27', nombre: 'Av. Casanova', tarifa_cliente_usd: 3.00, pago_repartidor_usd: 3.00, orden: 30, activo: true },
  { id: 'z28', nombre: 'Sabana Grande', tarifa_cliente_usd: 3.00, pago_repartidor_usd: 3.00, orden: 30, activo: true },
  { id: 'z29', nombre: 'Plaza Venezuela', tarifa_cliente_usd: 3.00, pago_repartidor_usd: 3.00, orden: 30, activo: true },
  { id: 'z30', nombre: 'Bello Monte', tarifa_cliente_usd: 3.00, pago_repartidor_usd: 3.00, orden: 30, activo: true },
  { id: 'z31', nombre: 'Helicoide', tarifa_cliente_usd: 3.00, pago_repartidor_usd: 3.00, orden: 30, activo: true },
  { id: 'z32', nombre: 'El Bosque', tarifa_cliente_usd: 4.00, pago_repartidor_usd: 4.00, orden: 40, activo: true },
  { id: 'z33', nombre: 'Lídice', tarifa_cliente_usd: 4.00, pago_repartidor_usd: 4.00, orden: 40, activo: true },
  { id: 'z34', nombre: 'Mercedores', tarifa_cliente_usd: 4.00, pago_repartidor_usd: 4.00, orden: 40, activo: true },
  { id: 'z35', nombre: 'Catia', tarifa_cliente_usd: 4.00, pago_repartidor_usd: 4.00, orden: 40, activo: true },
  { id: 'z36', nombre: 'Los Robles', tarifa_cliente_usd: 4.00, pago_repartidor_usd: 4.00, orden: 40, activo: true },
  { id: 'z37', nombre: '23 de Enero', tarifa_cliente_usd: 4.00, pago_repartidor_usd: 4.00, orden: 40, activo: true },
  { id: 'z38', nombre: 'Alta Vista', tarifa_cliente_usd: 4.00, pago_repartidor_usd: 4.00, orden: 40, activo: true },
  { id: 'z39', nombre: 'Cutira', tarifa_cliente_usd: 4.00, pago_repartidor_usd: 4.00, orden: 40, activo: true },
  { id: 'z40', nombre: 'Polvorín', tarifa_cliente_usd: 4.00, pago_repartidor_usd: 4.00, orden: 40, activo: true },
  { id: 'z41', nombre: 'Cota 905', tarifa_cliente_usd: 4.00, pago_repartidor_usd: 4.00, orden: 40, activo: true },
  { id: 'z42', nombre: 'La Ceiba', tarifa_cliente_usd: 4.00, pago_repartidor_usd: 4.00, orden: 40, activo: true },
  { id: 'z43', nombre: 'Alta Florida', tarifa_cliente_usd: 4.00, pago_repartidor_usd: 4.00, orden: 40, activo: true },
  { id: 'z44', nombre: 'Chapellín', tarifa_cliente_usd: 4.00, pago_repartidor_usd: 4.00, orden: 40, activo: true },
  { id: 'z45', nombre: 'Chacao', tarifa_cliente_usd: 4.00, pago_repartidor_usd: 4.00, orden: 40, activo: true },
  { id: 'z46', nombre: 'La Castellana', tarifa_cliente_usd: 4.00, pago_repartidor_usd: 4.00, orden: 40, activo: true },
  { id: 'z47', nombre: 'Altamira', tarifa_cliente_usd: 4.00, pago_repartidor_usd: 4.00, orden: 40, activo: true },
  { id: 'z48', nombre: 'Los Palos Grandes', tarifa_cliente_usd: 4.00, pago_repartidor_usd: 4.00, orden: 40, activo: true },
  { id: 'z49', nombre: 'Santa María', tarifa_cliente_usd: 4.00, pago_repartidor_usd: 4.00, orden: 40, activo: true },
  { id: 'z50', nombre: 'Montalbán', tarifa_cliente_usd: 4.00, pago_repartidor_usd: 4.00, orden: 40, activo: true },
  { id: 'z51', nombre: 'Los Dos Caminos', tarifa_cliente_usd: 4.00, pago_repartidor_usd: 4.00, orden: 40, activo: true },
  { id: 'z52', nombre: 'Monte Cristo', tarifa_cliente_usd: 4.00, pago_repartidor_usd: 4.00, orden: 40, activo: true },
  { id: 'z53', nombre: 'La Carlota', tarifa_cliente_usd: 4.00, pago_repartidor_usd: 4.00, orden: 40, activo: true },
  { id: 'z54', nombre: 'Chaguaramos', tarifa_cliente_usd: 4.00, pago_repartidor_usd: 4.00, orden: 40, activo: true },
  { id: 'z55', nombre: 'Las Mercedes', tarifa_cliente_usd: 4.00, pago_repartidor_usd: 4.00, orden: 40, activo: true },
  { id: 'z56', nombre: 'El Valle', tarifa_cliente_usd: 4.00, pago_repartidor_usd: 4.00, orden: 40, activo: true },
  { id: 'z57', nombre: 'La Yaguara', tarifa_cliente_usd: 4.00, pago_repartidor_usd: 4.00, orden: 40, activo: true },
  { id: 'z58', nombre: 'El Cementerio', tarifa_cliente_usd: 4.00, pago_repartidor_usd: 4.00, orden: 40, activo: true },
  { id: 'z59', nombre: 'Av. Roosvelt', tarifa_cliente_usd: 4.00, pago_repartidor_usd: 4.00, orden: 40, activo: true },
  { id: 'z60', nombre: 'La Bandera', tarifa_cliente_usd: 4.00, pago_repartidor_usd: 4.00, orden: 40, activo: true },
  { id: 'z61', nombre: 'Fuerte Tiuna', tarifa_cliente_usd: 4.00, pago_repartidor_usd: 4.00, orden: 40, activo: true },
  { id: 'z62', nombre: 'San Martín', tarifa_cliente_usd: 4.00, pago_repartidor_usd: 4.00, orden: 40, activo: true },
  { id: 'z63', nombre: 'Los Naranjos', tarifa_cliente_usd: 4.00, pago_repartidor_usd: 4.00, orden: 40, activo: true },
  { id: 'z64', nombre: 'Sebucán', tarifa_cliente_usd: 5.00, pago_repartidor_usd: 5.00, orden: 50, activo: true },
  { id: 'z65', nombre: 'Artigas', tarifa_cliente_usd: 5.00, pago_repartidor_usd: 5.00, orden: 50, activo: true },
  { id: 'z66', nombre: 'Pérez Bonalde', tarifa_cliente_usd: 5.00, pago_repartidor_usd: 5.00, orden: 50, activo: true },
  { id: 'z67', nombre: 'La Urbina', tarifa_cliente_usd: 5.00, pago_repartidor_usd: 5.00, orden: 50, activo: true },
  { id: 'z68', nombre: 'Boleíta', tarifa_cliente_usd: 5.00, pago_repartidor_usd: 5.00, orden: 50, activo: true },
  { id: 'z69', nombre: 'Los Ruices', tarifa_cliente_usd: 5.00, pago_repartidor_usd: 5.00, orden: 50, activo: true },
  { id: 'z70', nombre: 'El Márquez', tarifa_cliente_usd: 5.00, pago_repartidor_usd: 5.00, orden: 50, activo: true },
  { id: 'z71', nombre: 'La California', tarifa_cliente_usd: 5.00, pago_repartidor_usd: 5.00, orden: 50, activo: true },
  { id: 'z72', nombre: 'Prados del Este', tarifa_cliente_usd: 5.00, pago_repartidor_usd: 5.00, orden: 50, activo: true },
  { id: 'z73', nombre: 'Santa Fe', tarifa_cliente_usd: 5.00, pago_repartidor_usd: 5.00, orden: 50, activo: true },
  { id: 'z74', nombre: 'Valle Arriba', tarifa_cliente_usd: 5.00, pago_repartidor_usd: 5.00, orden: 50, activo: true },
  { id: 'z75', nombre: 'La Alameda', tarifa_cliente_usd: 5.00, pago_repartidor_usd: 5.00, orden: 50, activo: true },
  { id: 'z76', nombre: 'Petare', tarifa_cliente_usd: 5.00, pago_repartidor_usd: 5.00, orden: 50, activo: true },
  { id: 'z77', nombre: 'La Vega', tarifa_cliente_usd: 5.00, pago_repartidor_usd: 5.00, orden: 50, activo: true },
  { id: 'z78', nombre: 'Carapita', tarifa_cliente_usd: 5.00, pago_repartidor_usd: 5.00, orden: 50, activo: true },
  { id: 'z79', nombre: 'Antímano', tarifa_cliente_usd: 5.00, pago_repartidor_usd: 5.00, orden: 50, activo: true },
  { id: 'z80', nombre: 'El Cafetal', tarifa_cliente_usd: 5.00, pago_repartidor_usd: 5.00, orden: 50, activo: true },
  { id: 'z81', nombre: 'Santa Inés', tarifa_cliente_usd: 5.00, pago_repartidor_usd: 5.00, orden: 50, activo: true },
  { id: 'z82', nombre: 'Peñón', tarifa_cliente_usd: 5.00, pago_repartidor_usd: 5.00, orden: 50, activo: true },
  { id: 'z83', nombre: 'Cochecito', tarifa_cliente_usd: 5.00, pago_repartidor_usd: 5.00, orden: 50, activo: true },
  { id: 'z84', nombre: 'La Silsa', tarifa_cliente_usd: 5.00, pago_repartidor_usd: 5.00, orden: 50, activo: true },
  { id: 'z85', nombre: 'Vista Alegre', tarifa_cliente_usd: 5.00, pago_repartidor_usd: 5.00, orden: 50, activo: true },
  { id: 'z86', nombre: 'Santa Paula', tarifa_cliente_usd: 5.00, pago_repartidor_usd: 5.00, orden: 50, activo: true },
  { id: 'z87', nombre: 'Mamera', tarifa_cliente_usd: 5.00, pago_repartidor_usd: 5.00, orden: 50, activo: true },
  { id: 'z88', nombre: 'La Rinconada', tarifa_cliente_usd: 6.00, pago_repartidor_usd: 6.00, orden: 60, activo: true },
  { id: 'z89', nombre: 'Ruiz Pineda', tarifa_cliente_usd: 6.00, pago_repartidor_usd: 6.00, orden: 60, activo: true },
  { id: 'z90', nombre: 'Caricuao', tarifa_cliente_usd: 6.00, pago_repartidor_usd: 6.00, orden: 60, activo: true },
  { id: 'z91', nombre: 'Piedra Azul', tarifa_cliente_usd: 6.00, pago_repartidor_usd: 6.00, orden: 60, activo: true },
  { id: 'z92', nombre: 'Las Mayas', tarifa_cliente_usd: 6.00, pago_repartidor_usd: 6.00, orden: 60, activo: true },
  { id: 'z93', nombre: 'Trinidad', tarifa_cliente_usd: 6.00, pago_repartidor_usd: 6.00, orden: 60, activo: true },
  { id: 'z94', nombre: 'La Tahona', tarifa_cliente_usd: 6.00, pago_repartidor_usd: 6.00, orden: 60, activo: true },
  { id: 'z95', nombre: 'El Hatillo', tarifa_cliente_usd: 6.00, pago_repartidor_usd: 6.00, orden: 60, activo: true },
  { id: 'z96', nombre: 'Macaracuay', tarifa_cliente_usd: 6.00, pago_repartidor_usd: 6.00, orden: 60, activo: true },
  { id: 'z97', nombre: 'Palo Verde', tarifa_cliente_usd: 6.00, pago_repartidor_usd: 6.00, orden: 60, activo: true },
  { id: 'z98', nombre: 'La Bonita', tarifa_cliente_usd: 6.00, pago_repartidor_usd: 6.00, orden: 60, activo: true },
  { id: 'z99', nombre: 'Propatria', tarifa_cliente_usd: 6.00, pago_repartidor_usd: 6.00, orden: 60, activo: true },
  { id: 'z100', nombre: 'Casalta', tarifa_cliente_usd: 6.00, pago_repartidor_usd: 6.00, orden: 60, activo: true },
  { id: 'z101', nombre: 'Cruz del Este', tarifa_cliente_usd: 6.00, pago_repartidor_usd: 6.00, orden: 60, activo: true },
  { id: 'z102', nombre: 'Punto Fijo', tarifa_cliente_usd: 7.00, pago_repartidor_usd: 7.00, orden: 70, activo: true },
  { id: 'z103', nombre: 'Alto Hatillo', tarifa_cliente_usd: 7.00, pago_repartidor_usd: 7.00, orden: 70, activo: true },
]
